name: Build & Deploy site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Setup PNPM environment
        uses: pnpm/action-setup@v4
        with:
          version: 9.3.0

      - name: Install dependencies & build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build    

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: winstonmarvel.com